project.clj
Since we are now public, we should be pushing to clojars instead
of our internal repository.
Signed-off-by: Ken Barber <ken@bob.sh>
=> (PDB-2058) Modify project.clj for publishing to clojars

src/puppetlabs/ezbake/dependency_utils.clj
In previous commits, ezbake would only try to pull an ezbake.conf file
from upstream dependencies of the jar being packaged.  This commit changes
the logic to also pull in an ezbake.conf file that may be embedded in
the immediate project jar.
=> (EZ-57) Attempt to pull ezbake.conf from both project and upstream jars

CHANGELOG.md, src/puppetlabs/ezbake/core.clj
Currently, in our testing environment we are occasionally
seeing services timeout on startup at boot. This increases
the default startup timeout to 300 seconds (from 180).
There are a few ways to try and resolve this, this is the most expedient to
try to resolve intermittent issues in testing.
=> (PE-12468) Increase service start timeout to 300 seconds

resources/puppetlabs/lein-ezbake/template/pe/ext/redhat/init.suse.erb
If a logfile doesn't exist, startproc will create it as root, not the
user the process is starting at. This will touch the logfile if it
doesn't exist and chown it so that processes started with startproc will
be able to log.
=> (maint) startproc doesn't manage logfile permissions

resources/puppetlabs/lein-ezbake/template/foss/ext/redhat/ezbake.spec.erb, resources/puppetlabs/lein-ezbake/template/global/install.sh.erb, resources/puppetlabs/lein-ezbake/template/pe/ext/redhat/ezbake.spec.erb
Prior to this commit, Ezbake packages install the
'projconfdir' with 'root:root' ownership and
'755' permissions.
We should probably remove read/execute permissions
to this directory for the 'other/world' group, but
preserve the same permissions for project service
accounts.
This commit updates Ezbake to (1) install the
'projconfdir' with '750' permissions and (2) set
user/group ownership to a project's specific
user and group.
=> (RE-6278) Update permissions for "projconfdir".

src/puppetlabs/ezbake/dependency_utils.clj
This commit improves the places where ezbake calls into
pomegranate/aether to make sure that we are passing through
the value for the `mirrors` setting from the project (or
from the user profile), so that aether will look for artifacts
in our nexus repository before going out to clojars or
maven central.  This should improve performance and reduce
network I/O for our CI jobs, and help prevent inflating
our clojars download counts from CI jobs.
This change seems like an improvement and step forward regardless
of the version of leiningen that is being used, but until
technomancy/leiningen#2089 is resolved, there may still be
portions of our CI jobs that incorrectly ignore `:local-repo` /
`:mirrors` settings from the user profile.
=> (EZ-59) Pass mirrors setting to aether

resources/puppetlabs/lein-ezbake/template/foss/ext/redhat/ezbake.service.erb, resources/puppetlabs/lein-ezbake/template/pe/ext/redhat/ezbake.service.erb
To remedy some reoccuring issues with services needing a restart
this comit will add restart=on-failure and startlimitburst=5
to the service file for rpms. refer to further discussion at
https://tickets.puppetlabs.com/browse/RE-5962
Note that on-failure has been available in systemd since v12 [https://github.com/systemd/systemd/releases/tag/v12, systemd/systemd@50caaed]
and is supported on all the systemd platforms we support
=> (EZ-61) add restart=on-failure

resources/puppetlabs/lein-ezbake/template/global/ext/ezbake-functions.sh.erb
Ports sometimes are open before the app is really ready to accept
connections. Adding a 5s sleep after we detect the port is open to avoid
race conditions.
=> (EZ-76) Add sleep to wait_for_app

resources/puppetlabs/lein-ezbake/template/foss/ext/debian/control.erb
Prior to this commit, we were requiring virtual packages to satisfy java
runtime dependencies on deb based platforms. This was fine until we get
to Ubuntu 16.04 Xenial. On Xenial, Java7, Java8, and Java9 all provide
java8-runtime-headless. This is a problem, because it means that java9
is automatically installed to satisfy the specified runtime requirement
of java8-runtime-headless. We're not ready to update puppetserver with
Java9 support yet.
This commit switches from the virtual packages to the actual java
package that we want installed.
=> (maint) Do not use virtual package for java dep

resources/puppetlabs/lein-ezbake/template/global/install.sh.erb
Variable substitution issues were causing both deb and el to get set to
the el values for defaultsdir and unitdir. This fixes that issue.
=> (maint) Fix defaultsdir and unitdir

resources/puppetlabs/lein-ezbake/template/pe/ext/build_defaults.yaml
This will be required to build for 16.10 in ezbake projects
=> (maint) add the Ubuntu 16.10 (Xenial) cow to pe build defaults

resources/puppetlabs/lein-ezbake/template/global/install.sh.erb
For debian init scripts we cannot use real_name because it resolves to the
wrong thing. change this behavior to use EZBake::Config[:project]
=> (maint) update name field in init scripts

resources/puppetlabs/lein-ezbake/template/foss/ext/default.erb, resources/puppetlabs/lein-ezbake/template/pe/ext/default.erb
In systemd, it doesn't appear that variable interpolation is supported
inside of the defaults files.  Prior to this commit, when using
the `services-d` option for bootstrap configuration, we were generating
a defaults file that relied on interpolation.  This commit changes
the code to avoid the interpolation.
=> (SERVER-1247) fix bug with services-d bootstrap on systemd

resources/puppetlabs/lein-ezbake/template/foss/ext/redhat/ezbake.service.erb, resources/puppetlabs/lein-ezbake/template/foss/ext/redhat/init.erb, resources/puppetlabs/lein-ezbake/template/pe/ext/debian/ezbake.init.erb, resources/puppetlabs/lein-ezbake/template/pe/ext/redhat/ezbake.service.erb, resources/puppetlabs/lein-ezbake/template/pe/ext/redhat/init.erb, resources/puppetlabs/lein-ezbake/template/pe/ext/redhat/init.suse.erb
This commit backports the removal of the "HeapDumpOnOutOfMemoryError"
changes to the stable branch, so that we can include them if we
end up doing one more Puppet Server 1.x release.
(The original commit in the master branch is [here](https://github.com/puppetlabs/ezbake/commit/4d906dbe264cd32766d0c48d33aa8154afbb32df) ; it wouldn't cherry-pick cleanly so I did it by hand.)
=> (SERVER-1304) Backport removal of heap dump to stable branch

resources/puppetlabs/lein-ezbake/template/foss/ext/debian/ezbake.init.erb, resources/puppetlabs/lein-ezbake/template/foss/ext/debian/ezbake.service.erb, resources/puppetlabs/lein-ezbake/template/foss/ext/redhat/ezbake.service.erb, resources/puppetlabs/lein-ezbake/template/foss/ext/redhat/init.erb, resources/puppetlabs/lein-ezbake/template/pe/ext/debian/ezbake.init.erb, resources/puppetlabs/lein-ezbake/template/pe/ext/debian/ezbake.service.erb, resources/puppetlabs/lein-ezbake/template/pe/ext/redhat/ezbake.service.erb, resources/puppetlabs/lein-ezbake/template/pe/ext/redhat/init.erb, resources/puppetlabs/lein-ezbake/template/pe/ext/redhat/init.suse.erb
Set the default privileges to rw-r----- (permissions 640) so files are not world readable, even if moved out of the properly permissioned parent directories.
=> (EZ-83) Update init scripts to set a UMASK of 027

resources/puppetlabs/lein-ezbake/staging-templates/ezbake.rb.mustache, resources/puppetlabs/lein-ezbake/template/foss/ext/debian/ezbake.init.erb, resources/puppetlabs/lein-ezbake/template/foss/ext/debian/ezbake.service.erb, resources/puppetlabs/lein-ezbake/template/foss/ext/default.erb, resources/puppetlabs/lein-ezbake/template/foss/ext/redhat/ezbake.service.erb, resources/puppetlabs/lein-ezbake/template/foss/ext/redhat/init.erb, resources/puppetlabs/lein-ezbake/template/pe/ext/debian/ezbake.init.erb, resources/puppetlabs/lein-ezbake/template/pe/ext/debian/ezbake.service.erb, resources/puppetlabs/lein-ezbake/template/pe/ext/default.erb, resources/puppetlabs/lein-ezbake/template/pe/ext/redhat/ezbake.service.erb, resources/puppetlabs/lein-ezbake/template/pe/ext/redhat/init.erb, resources/puppetlabs/lein-ezbake/template/pe/ext/redhat/init.suse.erb, src/puppetlabs/ezbake/core.clj
Allows ezbake projects to configure a default open file limit as part of
service startup.
=> (EZ-86) Add configuration of open file limit to services

resources/puppetlabs/lein-ezbake/template/foss/ext/redhat/init.erb, resources/puppetlabs/lein-ezbake/template/pe/ext/redhat/init.erb
Prior to this commit, the EL init script's "find_my_pid" function
creates an empty pidfile if the service is not running.
This commit updates the "find_my_pid" function to check that $pid is not
a zero-length string before writing a pidfile.
=> (EZ-84) Don't create empty pidfile if there's no pid

resources/puppetlabs/lein-ezbake/staging-templates/ezbake.rb.mustache, src/puppetlabs/ezbake/core.clj
This PR fixes a parse error that was cause by `open_file_limit` being wrapped in quotes. This caused it to always be set which caused parse errors on systemd. This was fixed by removing the quotes in the mustache template and explicitly defining `nil` as a string rather than a nil value in core.clj. This allowed it to become nil once the mustache template is evaluated.
=> (MAINT) fix LimitNOFILE parse error

README_BRANCHING.md, resources/puppetlabs/lein-ezbake/template/global/ext/cli/reload.erb, resources/puppetlabs/lein-ezbake/template/global/ext/cli/start.erb
This is a fixup PR, changes two typos in EZBake.
=> (EZ-68) fix typo `EZbake` to `EZBake`

resources/puppetlabs/lein-ezbake/template/foss/ext/build_defaults.yaml, resources/puppetlabs/lein-ezbake/template/foss/ext/redhat/ezbake.spec.erb
This unfortunately will not work for builds outside of the puppetlabs
ecosystem. There are no publicly available sles mirrors available, so we
have created our own in house mirror. This is not available to the
public. The sles mocks created with the rpmbuilder module are configured
to hit this internal repo, but to not fail if the user doesn't have
access to it.
=> (RE-7420) Build FOSS ezbake projects on sles

resources/puppetlabs/lein-ezbake/template/foss/ext/debian/ezbake.init.erb, resources/puppetlabs/lein-ezbake/template/foss/ext/debian/ezbake.service.erb, resources/puppetlabs/lein-ezbake/template/foss/ext/redhat/ezbake.service.erb, resources/puppetlabs/lein-ezbake/template/foss/ext/redhat/init.erb, resources/puppetlabs/lein-ezbake/template/global/ext/cli/start.erb, resources/puppetlabs/lein-ezbake/template/pe/ext/debian/ezbake.init.erb, resources/puppetlabs/lein-ezbake/template/pe/ext/debian/ezbake.service.erb, resources/puppetlabs/lein-ezbake/template/pe/ext/redhat/ezbake.service.erb, resources/puppetlabs/lein-ezbake/template/pe/ext/redhat/init.erb, resources/puppetlabs/lein-ezbake/template/pe/ext/redhat/init.suse.erb
Previously, system init scripts would daemonize a java process and then use a post-start command to poll for the port to open with netstat. This PR includes the new start script which will both daemonize a java process and poll for the service status using a restart-file implemented in [TK-345](https://github.com/puppetlabs/trapperkeeper/pull/248). The service scripts have been changed to call on this new `start` subcommand.
=> (EZ-70) Modify service 'start' functionality to use new TK 'start' subcommand

README.md, resources/puppetlabs/lein-ezbake/staging-templates/ezbake.rb.mustache, resources/puppetlabs/lein-ezbake/template/foss/ext/debian/rules.erb, resources/puppetlabs/lein-ezbake/template/foss/ext/redhat/ezbake.spec.erb, resources/puppetlabs/lein-ezbake/template/pe/ext/debian/rules.erb, resources/puppetlabs/lein-ezbake/template/pe/ext/redhat/ezbake.spec.erb, src/puppetlabs/ezbake/core.clj
This commit adds a new boolean ezbake setting to disable logrotate in a project
SERVER-366 covers work to limit the amount of disk space puppetserver will use for its logs. We decided to accomplish that by utilizing the built in features of the logback library. Logback will
* Do daily rotating of logs
* Rotate the logs out once they reach a certain size
* Limit the total size of all the puppetserver log file
Logrotate is no longer needed, so we needed a way to disable logrotate in ezbake. The change in this PR is backwards compatible, as it defaults to turning logrotate on.
=> (SERVER-366) Add boolean to disable logrotate

CHANGELOG.md
Changlog:
* Add `:logrotate-enabled` setting to allow disabling of logrotate. Enabled
by default.
Note: While technically a minor feature release, this is going to be a Z
release to avoid branch renaming hassles.
=> (MAINT) Update changelog for 0.2.13 release

README.md, resources/puppetlabs/lein-ezbake/staging-templates/ezbake.rb.mustache, resources/puppetlabs/lein-ezbake/template/foss/ext/debian/rules.erb, resources/puppetlabs/lein-ezbake/template/foss/ext/redhat/ezbake.spec.erb, resources/puppetlabs/lein-ezbake/template/pe/ext/debian/rules.erb, resources/puppetlabs/lein-ezbake/template/pe/ext/redhat/ezbake.spec.erb, src/puppetlabs/ezbake/core.clj
This is a merge up of changes in SERVER-366 from `0.2.x` to `master`
SERVER-366 covers work to limit the amount of disk space puppetserver will use
for its logs. We decided to accomplish that by utilizing the built in features
of the logback library. Logback will:
* Do daily rotating of logs
* Rotate the logs out once they reach a certain size
* Limit the total size of all the puppetserver log file
Logrotate is no longer needed, so we needed a way to disable logrotate in ezbake.
The change in this commit is backwards compatible, as it defaults to turning
logrotate on.
=> (EZ-95) Merge up logback changes from 0.2.x to master

README.md, resources/puppetlabs/lein-ezbake/staging-templates/ezbake.rb.mustache, resources/puppetlabs/lein-ezbake/template/foss/ext/debian/rules.erb, resources/puppetlabs/lein-ezbake/template/foss/ext/redhat/ezbake.spec.erb, resources/puppetlabs/lein-ezbake/template/pe/ext/debian/rules.erb, resources/puppetlabs/lein-ezbake/template/pe/ext/redhat/ezbake.spec.erb, src/puppetlabs/ezbake/core.clj
This commit merges the changes from server-366 from 0.2.x to stable
SERVER-366 covers work to limit the amount of disk space puppetserver will use
for its logs.
----
**Note:** We accidentally merged this to master earlier. This is harmless as we would have needed to merge it up to master eventually anyways.
=> (EZ-95) merge 0.2.x to stable

resources/puppetlabs/lein-ezbake/template/foss/ext/debian/ezbake.init.erb, resources/puppetlabs/lein-ezbake/template/pe/ext/debian/ezbake.init.erb
This commit fixes a bug introduced by EZ-70 where the start and stop
actions in Debian init scripts would errantly return a 1 (failure) exit
code when the start/stop succeeded rather than returning a 0.
=> (EZ-96) Exit with appropriate codes for start/stop in Debian init script

resources/puppetlabs/lein-ezbake/template/foss/ext/debian/ezbake.init.erb, resources/puppetlabs/lein-ezbake/template/global/ext/cli/reload.erb, resources/puppetlabs/lein-ezbake/template/global/ext/cli/start.erb, resources/puppetlabs/lein-ezbake/template/pe/ext/debian/ezbake.init.erb
This PR primarily handles terminating the "wait for" loops immediately if the Java process spawned by the start or reload commands dies.  Previously, the commands would wait for a full configured "timeout" to expire before terminating.  In the process of hooking this up, I found a few related bugs around start functionality which are addressed in this PR, including:
* If the start script is terminated - e.g., by systemctl under systemd - while still running, the associated Java process is now terminated as well.  Previously, the Java process could continue running, leaving the resulting service in an inconsistent state (depending upon timing) from the service framework's perspective.
* Handle an exit code of "1" under Debian init as a failure instead of as a success.  Previously, the …
=> (EZ-97) Start / reload commands should error immediately after Java process dies

resources/puppetlabs/lein-ezbake/staging-templates/ezbake.rb.mustache, resources/puppetlabs/lein-ezbake/template/foss/ext/debian/control.erb, resources/puppetlabs/lein-ezbake/template/foss/ext/redhat/ezbake.spec.erb, resources/puppetlabs/lein-ezbake/template/global/install.sh.erb, resources/puppetlabs/lein-ezbake/template/pe/ext/debian/control.erb, resources/puppetlabs/lein-ezbake/template/pe/ext/redhat/ezbake.spec.erb, src/puppetlabs/ezbake/core.clj
This adds per-project build dependencies to ezbake, allowing projects to declare build deps in the same was as runtime deps for packaging.
This also adds the contents of the project data directory to packaging, instead of just packaging the top-level data directory. This allows package builds to install files there and have them picked up by packaging.
=> (EZ-88) Add per-project build dependencies

resources/puppetlabs/lein-ezbake/template/foss/ext/debian/control.erb, resources/puppetlabs/lein-ezbake/template/foss/ext/debian/ezbake.init.erb, resources/puppetlabs/lein-ezbake/template/foss/ext/debian/ezbake.service.erb, resources/puppetlabs/lein-ezbake/template/foss/ext/redhat/ezbake.service.erb, resources/puppetlabs/lein-ezbake/template/foss/ext/redhat/ezbake.spec.erb, resources/puppetlabs/lein-ezbake/template/foss/ext/redhat/init.erb, resources/puppetlabs/lein-ezbake/template/global/ext/cli/reload.erb, resources/puppetlabs/lein-ezbake/template/global/ext/cli/start.erb, resources/puppetlabs/lein-ezbake/template/global/ext/cli/stop.erb, resources/puppetlabs/lein-ezbake/template/global/ext/ezbake-functions.sh.erb, resources/puppetlabs/lein-ezbake/template/pe/ext/debian/control.erb, resources/puppetlabs/lein-ezbake/template/pe/ext/debian/ezbake.init.erb, resources/puppetlabs/lein-ezbake/template/pe/ext/debian/ezbake.service.erb, resources/puppetlabs/lein-ezbake/template/pe/ext/redhat/ezbake.service.erb, resources/puppetlabs/lein-ezbake/template/pe/ext/redhat/ezbake.spec.erb, resources/puppetlabs/lein-ezbake/template/pe/ext/redhat/init.erb, resources/puppetlabs/lein-ezbake/template/pe/ext/redhat/init.suse.erb
This PR adds a TK stop subcommand script, which just gets the pid of
the service process, calls the kill_pid function to kill it, and nukes
the associated service pidfile.  This PR also modifies all of the OS init
scripts / systemd service definitions to invoke the new TK stop
subcommand to stop a service.
The commit also inlines some fully-qualified uses of
/opt/puppetlabs/server/apps/<app_name> with references to
$INSTALL_DIR, where possible.
For the SLES 11 init script, the startproc command line was also fixed
up such that the process will actually be started correctly and some
excess log message logic was removed.
=> (EZ-99) Introduce TK stop script and call from service stop

resources/puppetlabs/lein-ezbake/staging-templates/ezbake.rb.mustache, resources/puppetlabs/lein-ezbake/template/foss/ext/debian/ezbake.service.erb, resources/puppetlabs/lein-ezbake/template/foss/ext/default.erb, resources/puppetlabs/lein-ezbake/template/foss/ext/redhat/ezbake.service.erb, resources/puppetlabs/lein-ezbake/template/global/ext/cli/reload.erb, resources/puppetlabs/lein-ezbake/template/global/ext/cli/start.erb, resources/puppetlabs/lein-ezbake/template/global/ext/cli/stop.erb, resources/puppetlabs/lein-ezbake/template/global/ext/ezbake-functions.sh.erb, resources/puppetlabs/lein-ezbake/template/pe/ext/debian/ezbake.service.erb, resources/puppetlabs/lein-ezbake/template/pe/ext/default.erb, resources/puppetlabs/lein-ezbake/template/pe/ext/redhat/ezbake.service.erb, src/puppetlabs/ezbake/core.clj
This PR adds optional Ezbake config timeout settings for reload and stop, defaulting to 2 minutes and 60 seconds, respectively.  The settings are attached to the new `RELOAD_TIMEOUT` and pre-existing `SERVICE_STOP_TIMEOUT` default/sysconfig settings.
The PR also includes some code to terminate the Java process if the start timeout is reached during a startup attempt.
=> (EZ-100) Add timeout settings for reload and stop

README.md, resources/puppetlabs/lein-ezbake/staging-templates/ezbake.rb.mustache, resources/puppetlabs/lein-ezbake/template/global/ext/cli/foreground.erb, resources/puppetlabs/lein-ezbake/template/global/ext/cli/reload.erb, resources/puppetlabs/lein-ezbake/template/global/ext/cli/start.erb, resources/puppetlabs/lein-ezbake/template/global/ext/ezbake-functions.sh.erb, src/puppetlabs/ezbake/core.clj
This PR adds "restart-file" to the Java command lines in the start
and foreground scripts and eliminates the use of a "restart-file"
EzBake config option for determining the location of the file.  EzBake
instead uses a default for the file which is based on the "realname"
of the package, `/opt/puppetlabs/server/data/[pkg-name]/restartcounter`,
and no longer has to depend upon corresponding TK global
configuration to be set to the same value in order for a service to be
started properly.
=> (EZ-101) Specify restart file option via TK command line

resources/puppetlabs/lein-ezbake/staging-templates/cli-app.erb
In EZ-83, work was done across various init scripts / system service
definitions to set the default umask to 027.  Since some of the cli
subcommands - notably, foreground - are not typically initiated from an
init script / service context, they would still run with the default
system umask.  This commit adds the same explicit umask to the cli app
script for consistency - ensuring that when adhoc commands like
foreground are run that files like logs are not created with undesirable
world-accessible permissions.
=> (MAINT) Set umask to 027 in cli app script

src/puppetlabs/ezbake/core.clj
Prior to this commit, if you had made certain kinds of
changes to your local project and then run ezbake without
first running `lein install`, those changes would not get
included in the build, because ezbake pulls the jar from
the local m2 repo.
When this happened you'd usually lose at least 30 mins of
productivity in waiting for the builds and then debugging
them after they turned out not to match your local
environment.
This commit adds a call to `lein install` at the beginning
of `stage`, which will ensure that local changes are always
picked up when you run ezbake.
=> (MAINT) Run `lein install` before stage

src/puppetlabs/ezbake/core.clj
This commit adds support for creating an `ext/build-scripts/` dir
in a project's jar.  If found, ezbake will copy all of the files
found in this directory into the staging directory, so that they
will be included in the tarball that is sent up to the packaging
system.
These files will *not* be included in the final packages, but they
can be referenced during the package build, e.g. during the `install`
phase, in order to reduce duplication of logic in the ezbake config
files.
=> (SERVER-1412) Allow build scripts to be included in staging tarball

src/puppetlabs/ezbake/dependency_utils.clj
Prior to this commit, there were some places in ezbake where it
does things to resolve maven dependencies.  The relevant code
did not take into account the new `:managed-dependencies`
capabilities in lein 2.7.  This commit adds in the appropriate
handling of those dependencies where necessary.
=> (SERVER-1591) Handle managed dependencies

resources/puppetlabs/lein-ezbake/template/foss/ext/debian/ezbake.service.erb, resources/puppetlabs/lein-ezbake/template/foss/ext/redhat/ezbake.service.erb, resources/puppetlabs/lein-ezbake/template/pe/ext/debian/ezbake.service.erb, resources/puppetlabs/lein-ezbake/template/pe/ext/redhat/ezbake.service.erb
This is to document how to correctly set limits in an upgrade-safe way.
=> (maint) Add a comment about setting limits in the systemd service file

resources/puppetlabs/lein-ezbake/template/foss/ext/debian/ezbake.init.erb, resources/puppetlabs/lein-ezbake/template/foss/ext/redhat/init.erb, resources/puppetlabs/lein-ezbake/template/global/ext/cli/start.erb, resources/puppetlabs/lein-ezbake/template/global/ext/ezbake-functions.sh.erb, resources/puppetlabs/lein-ezbake/template/global/ext/ezbake.tmpfiles.conf.erb, resources/puppetlabs/lein-ezbake/template/global/install.sh.erb, resources/puppetlabs/lein-ezbake/template/pe/ext/debian/ezbake.init.erb, resources/puppetlabs/lein-ezbake/template/pe/ext/redhat/init.erb, resources/puppetlabs/lein-ezbake/template/pe/ext/redhat/init.suse.erb
Prior to this commit, we had been creating the rundir, but sometimes
with permissions which prevented the service from being able to create
its own pidfile.  In these cases, the Java process could be launched
successfully and the service start command could still return success.
Any subsequent attempts to ask the service framework for status on the
service, however, would return failure (not started).
This commit should ensure that the rundir is always created with
permissions which allow the service to create its own pidfile.  This
commit also adds some error handling to return failure at service
startup if the pidfile unexpectedly could not be written for some
reason.
=> (EZ-103) Address incorrect rundir perms

resources/puppetlabs/lein-ezbake/template/global/ext/cli/start.erb
This commit restores the -XX:OnOutOfMemoryError / kill -9 command line
argument to the Java command line in the start script.  This was
previously unintentionally lost in the conversion of the Java command
line construction from the init scripts and systemd service definitions
over to the start script.
=> (EZ-104) Restore missing oom command line argument

resources/puppetlabs/lein-ezbake/template/foss/ext/debian/postinst.erb, resources/puppetlabs/lein-ezbake/template/foss/ext/debian/prerm.erb, resources/puppetlabs/lein-ezbake/template/foss/ext/debian/rules.erb, resources/puppetlabs/lein-ezbake/template/global/install.sh.erb, resources/puppetlabs/lein-ezbake/template/pe/ext/debian/postinst.erb, resources/puppetlabs/lein-ezbake/template/pe/ext/debian/prerm.erb, resources/puppetlabs/lein-ezbake/template/pe/ext/debian/rules.erb
This commit updates EZBake to start installing sysv files on newer
systemd based debian-ish systems. The idea being that users should be
able to switch between the older and newer service management tools.
This is a behavior that has already been established in other packages
that are targeted at newer releases.
This commit also updates EZBake to provide native SystemD files for
Debian 8 Jessie. This had not previously been done because of concerns
over saving state on upgrade from SysV to SystemD. This is no longer a
concern.
=> (EZ-102) Update EZBake to install SysV + SystemD

resources/puppetlabs/lein-ezbake/template/foss/ext/redhat/ezbake.spec.erb, resources/puppetlabs/lein-ezbake/template/pe/ext/redhat/ezbake.spec.erb
Currently the generated RPM packages will automatically generate
a set of requirements based on the contents of the package. This
has become an issue with puppet-server 2.7.0, as adding gems
to the package inadvertently added a dependency on system ruby.
This adds 'AutoReq: 0' to the RPM specs to stop generating automatic
dependency information, and adds 'bash' as the only dependency
that was being automatically added that we still want.
This also adds 'AutoProv: 0' to stop generating a package 'provides'.
This should be unnecessary, but harmless and may save us some pain in
the future if we wind up shipping any shared libs in a package somewhere.
=> (SERVER-1670) Stop autogenerating dependencies for RPM packages

resources/puppetlabs/lein-ezbake/template/foss/ext/redhat/ezbake.spec.erb, resources/puppetlabs/lein-ezbake/template/pe/ext/redhat/ezbake.spec.erb
We add the dependency specifically on '/usr/bin/which' to be flexible
with minimal installers which may provide functionality from different
packages.
=> (CPR-401) Require 'which'

resources/puppetlabs/lein-ezbake/template/global/ext/cli/foreground.erb
This commit adds -Djava.security.egd=/dev/urandom as an argument to the
Java command line for the foreground subcommand.  This argument was
already being used in the service start subcommand.  Performance for some
operations like SSL can be significantly faster with this option in
place so it seems like having this benefit when troubleshooting with the
foreground subcommand would be a good thing.
=> (SERVER-1723) Use /dev/urandom for foreground subcommand

resources/puppetlabs/lein-ezbake/template/foss/ext/redhat/ezbake.spec.erb
Now that puppetserver has started bundling gems into the ezbake build,
java's lack of truststore anchors in our build has become a problem. In
jruby, simply requiring openssl will fail if there are no trust anchors.
This is the case on sles12. To avoid this problem, this commit adds the
correct ca-certificates package for el and for sles 12.
=> (SERVER-1763) Add ca-certificates as build dependency

src/puppetlabs/ezbake/core.clj, src/puppetlabs/ezbake/dependency_utils.clj
Change EZBake's stage command to:
1) Deploy an artifact to the configured snapshots repository when staging a project with a snapshot version.
2) List the deployed snapshot artifact's version as the project's version number in the ezbake.manifest & project_data.yaml files.
3) Resolve all dependencies with 'SNAPSHOT' versions to get a deployed snapshot artifact from the repository and list that artifact's version number in the ezbake.manifest & project_data.yaml. If no deployed snapshot artifacts can be found for the listed snapshot version, then an error is thrown and staging is aborted, to prevent unreproducible builds.
4) List each dependency's group as well as its name in the ezbake.manifest & project_data.yaml
See the individual commit mesages for more details.
=> (maint) Towards Transparent, Reproducible Snapshot Promotions

README.md, src/puppetlabs/ezbake/core.clj
Change the `stage` action to avoid deploying to the snapshots repository
if the `EZBAKE_NODEPLOY` environment variable is set to any value
(including `false` or `0` or `null`), and mention this in the README
=> (EZ-108) Don't deploy if `EZBAKE_NODEPLOY` set

README.md, src/puppetlabs/ezbake/core.clj, src/puppetlabs/ezbake/dependency_utils.clj
Backport the recently merged changes on master to list specific snapshot versions included in a package and to have the full dependency symbol (including the group) in the description.
=> (maint) Backport Snapshot-Version Changes & Full Dependency Names

resources/puppetlabs/lein-ezbake/staging-templates/project_data.yaml.mustache, src/puppetlabs/ezbake/core.clj
This commit allows ezbake to take advantage of a new feature in the
packaging repo. We can switch between a final and non-final repo
definition. This commit allows ezbake to set a value for that non-final
repo and for that setting to propagate through properly to the
automation in the packaging repo.
This means we can ship development builds with the same automation we
use to ship final builds. But the builds will be kept separate based on
if it's a final or non-final build (determined by the presence of
SNAPSHOT in the version name).
This is all in preparation for the change over to the puppet5 repos.
Before we have all the finalized puppet5 packages, we want to make
beta/development/nightly builds available on apt.puppetlabs.com,
yum.puppetlabs.com, and downloads.puppetlabs.com under a …
=> (RE-8726) Allow nonfinal repo definition

src/puppetlabs/ezbake/core.clj
This commit fixes an issue where some duplicate text would show up in
ezbake.manifest if additional uberjars were specified in the ezbake section of
a project.clj file
This was because of a combination of mustache being mustache, and because
`not-empty` returns its argument if it is not empty, rather than returning true.
This causes the mustache template to act unexpectedly.
`(not (empty? ...))` always returns a boolean and fixes the issue
=> (EZ-109) Fix duplicate text in ezbake.manifest

src/puppetlabs/ezbake/core.clj, src/puppetlabs/ezbake/dependency_utils.clj
Previously, the additional uberjar functionality appended the immediate
project jar as a dependency of itself in order for its content to be
generated into the uberjar.  This logic, however, did not work when the
project had any dependency overrides in the uberjar profile.  In that
case, none of the content from the immediate jar ended up in the uberjar
and the ezbake.manifest dependency info errantly listed info from the
main project's dependencies which did not end up in the uberjar.
In this PR, the immediate project's jar is appended directly into
the process of creating the uberjar - rather than as a self-referential
dependency.  This allows for the uberjar to properly retain content from
the main project jar even in the case of uberjar profile overrides.  The
main project's own …
=> (EZ-110) Fix ezbake manifest generation for dependency overrides

CHANGELOG.md, project.clj
This commit updates the CHANGELOG.md and project.clj version in
preparation for the 1.4.0 release.
=> (MAINT) Prep for 1.4.0 release

README.md
This commit changes the reference to the ezbake plugin version in the
README.md to use the Clojars badge for version info in place of the
hardcoded (and usually out of date) version being used previously.
=> (MAINT) Use Clojars badge in README

src/puppetlabs/ezbake/dependency_utils.clj
Before this commit we were only listing the dependencies which were
listed in the dependencies field which may not include everything. This
commit adds the managed dependencies to the list of dependencies to
consider when building out the dependency map.
=> (RE-8861) Add managed dependencies to dependency map

resources/puppetlabs/lein-ezbake/template/foss/ext/build_defaults.yaml, resources/puppetlabs/lein-ezbake/template/pe/ext/build_defaults.yaml
We still had precise and wily in our default cow list. We should remove
those, as both of those platforms are EOL.
=> (maint) Remove EOL ubuntu platforms from cow lists

resources/puppetlabs/lein-ezbake/template/foss/ext/build_defaults.yaml, resources/puppetlabs/lein-ezbake/template/pe/ext/build_defaults.yaml
We still had yakkety and precise in platform lists, but those are EOL so
let's get rid of those.
=> (maint) Remove EOL platforms from cow lists

resources/puppetlabs/lein-ezbake/staging-templates/ezbake.rb.mustache, resources/puppetlabs/lein-ezbake/template/global/ext/debian/docs.erb, resources/puppetlabs/lein-ezbake/template/global/ext/redhat/ezbake.spec.erb, resources/puppetlabs/lein-ezbake/template/global/install.sh.erb, src/puppetlabs/ezbake/core.clj
As we start exploring alternate packaging with ezbake, it's cleaner if
we let the install script put the docs in place as we do with all the
other files rather than installing those separately.
=> (maint) Move doc installation to install.sh

resources/puppetlabs/lein-ezbake/template/global/tasks/build.rake
Initially we were generating the packaging tarball then moving it into a
staging directory to prepare artifacts for the build step. However, we
should be shipping this tarball to builds, so let's copy it instead.
=> (maint) Make sure the packaging tarball is shipped

src/puppetlabs/ezbake/core.clj
The method to determine the release number was correctly setting the
release for SNAPSHOT builds but was errantly setting it to the version
if this was not a SNAPSHOT build. This fixes that method to return 1 for
non-SNAPSHOT builds, since we don't support custom release numbers.
=> (maint) Fix release for final versions

resources/puppetlabs/lein-ezbake/template/foss/ext/build_defaults.yaml, resources/puppetlabs/lein-ezbake/template/pe/ext/build_defaults.yaml
This will enable us to utilize new and improved utilities that are
available in this branch.
=> (maint) Update EZBake to pull from the 1.0.x branch of packaging

CHANGELOG.md, project.clj, resources/puppetlabs/lein-ezbake/staging-templates/ezbake.rb.mustache, resources/puppetlabs/lein-ezbake/template/foss/ext/build_defaults.yaml, resources/puppetlabs/lein-ezbake/template/global/controller.sh.erb, resources/puppetlabs/lein-ezbake/template/global/ext/debian/postinst.erb, resources/puppetlabs/lein-ezbake/template/global/ext/fpm.rb, resources/puppetlabs/lein-ezbake/template/pe/ext/build_defaults.yaml, src/puppetlabs/ezbake/core.clj
Especially since I found a bug that's going to require a 1.6.5, let's revert all the 1.7.0 stuff until that gets in, then rebuild 1.7.0 with the triggers stuff.
=> (maint) We accidentally released 1.7.0 as 1.6.4.  Let's fix this up good.

resources/puppetlabs/lein-ezbake/template/global/controller.sh.erb, resources/puppetlabs/lein-ezbake/template/global/ext/fpm.rb
When converting the existing packaging files to fpm, I missed the pass-throughs for `replaces_pkgs` and `create_dirs`.
=> (maint) Missed a couple of pass-throughs to fpm

resources/puppetlabs/lein-ezbake/template/global/ext/cli/reload.erb, resources/puppetlabs/lein-ezbake/template/global/ext/cli/start.erb, resources/puppetlabs/lein-ezbake/template/global/ext/cli/stop.erb
Previously, the start/stop/reload scripts would use a `pgrep` to search
for running processes, to determine if the service was still running.
That `pgrep` would do a simple search for uberjar name.
Turns out, that's not specific enough. In the case of puppetserver, a
user invocation of `puppetserver gem list` will put a process in the
process list that the naive `pgrep` would finger as the service pid in
the event puppetserver wasn't actually running. This could trick a
service manager into thinking puppetserver was running when in fact it
could be stopped for hours.
This commit doesn't change the basic service detection logic, but it
improves the `pgrep` to be more discerning, and search not only for the
uberjar name but also for the main namespace.
=> (SERVER-2068) Be more discerning finding PIDs

resources/puppetlabs/lein-ezbake/template/foss/ext/build_defaults.yaml
This reverts commit 8724f1b55b896bd41b541163d518adea5abee22e.
We were fixing a symptom of a problem, rather than the problem itself (see
RE-10238).
=> Revert "(maint) Add build_tar: FALSE to foss build_defaults"

resources/puppetlabs/lein-ezbake/template/global/ext/debian/ezbake.service.erb, resources/puppetlabs/lein-ezbake/template/global/ext/redhat/ezbake.service.erb
pe-puppetserver has a dependency on the network.target, which ensures that the network is started prior to starting the pe-puppetserver. However, the pe-puppetserver really needs the network to be online prior to starting if it has to do any DNS lookups. Since the service can start prior to the network coming online, it can cause nscd to cache a negative response to DNS lookups and delay the startup of the service.
=> (EZ-112) Don't start puppetserver until networking comes online

README.md
This commit removes a paragraph from the description of `ezbake stage` that
contains a duplicate explanation of the EZBAKE_NODEPLOY environment variable.
=> (maint) Remove duplicate paragraph from README

src/puppetlabs/ezbake/core.clj
We use timestamps for two separate parts of the `stage` action. Since
the timestamps only record the time to the minute, this only causes
issues when the timing is just right, but when it does it leads to
a mismatch in package version and the directory the packages are shipped
to.
This commit updates the stage action to generate the timestamp once and
pass it through to the functions that ultimately end up setting the
release field in ezbake.rb and tagging the git repo so we can be sure
we're using the same timestamp for both.
=> (EZ-124) Use consistent timestamps

README.md, resources/puppetlabs/lein-ezbake/staging-templates/Dockerfile.mustache, src/puppetlabs/ezbake/core.clj
This adds a new `lein ezbake docker-build` command which can be used to
generate a standardized docker image from a trapperkeeper project.
The resulting image has the requisite java invocation set as its
entrypoint, referring a bootstrap.cfg and conf.d both located at
/config, and setting the classpath set to the project uberjar and any
additional jars, which are placed into /src. The base image defaults to
openjdk:8-jre-alpine, but can be overridden in the project.clj. Ports
to be exposed can be included in project.clj, as well as the name to tag
the image with, which defaults to the project name.
=> (EZ-127) Add docker-build to build an image from a clojure repo

resources/puppetlabs/lein-ezbake/staging-templates/ezbake.rb.mustache, resources/puppetlabs/lein-ezbake/template/global/ext/redhat/preinst.erb, src/puppetlabs/ezbake/core.clj
For RPM packaging, we have a reserved uid/gid for the 'puppet' user. To
enable us to use the reserved uid/gid for the puppet user, ezbake needs
to support an option for that. The new option is `numeric-uid-gid`,
which can be set in the `:lein-ezbake` section of your project.clj.
This option is a noop for deb packaging. According to the debian policy
guide
(https://www.debian.org/doc/debian-policy/ch-opersys.html#uid-and-gid-classes)
reserved uids and gids need to be set in the `base-passwd` package.
=> (EZ-128) Add support for specifying numeric uid/gid in rpm packages

resources/puppetlabs/lein-ezbake/template/global/ext/debian/ezbake.service.erb, resources/puppetlabs/lein-ezbake/template/global/ext/redhat/ezbake.service.erb
In some versions of systemd (including versions in Ubuntu 16.04 and
SLES 12.2) TasksMax deaults to 512. This sets TasksMax for our
services to the default introduced in more recent systemd releases.
=> (EZ-129) Set TasksMax for systemd

resources/puppetlabs/lein-ezbake/staging-templates/ezbake.rb.mustache, resources/puppetlabs/lein-ezbake/template/foss/ext/default.erb, resources/puppetlabs/lein-ezbake/template/pe/ext/default.erb, src/puppetlabs/ezbake/core.clj
Puppet Server at least provides cli tools in addition to ezbake's
provided `start`, `stop`, `reload`. Those tools also need a way to
specify JAVA_ARGS but have Very different needs than the service. Puppet
Server therefore uses JAVA_ARGS_CLI to differentiate between the one
off CLI tools and the service.
This patch adds that JAVA_ARGS_CLI to the default file that ezbake
provides.
=> (SERVER-2399) List JAVA_ARGS_CLI in default file

resources/puppetlabs/lein-ezbake/template/global/ext/debian/ezbake.service.erb, resources/puppetlabs/lein-ezbake/template/global/ext/redhat/ezbake.service.erb
Users were still seeing errors after the change made here: https://github.com/puppetlabs/ezbake/pull/477. ~~The new change was suggested by Redhat so I'm not sure if we want to use this for debian as well?~~ I've tested with rpms now working on debs and will have info on the tests up in a little bit
=> (EZ-112) Use nss-lookup.target instead of network-online.target

resources/puppetlabs/lein-ezbake/template/foss/ext/default.erb
Prior to this we would overwrite any value of JAVA_ARGS_CLI set on the
command line when we sourced the defaults file. This updates the
defaults file to respect any previously set value for the variable.
=> (maint) Honor JAVA_ARGS_CLI values set in the command line

resources/puppetlabs/lein-ezbake/template/pe/ext/default.erb
And other tales from "Things You Miss When You Update Work After A Two Week Vacation".
=> (maint) Fix PE default file to match FOSS wrt JAVA_ARGS_CLI

resources/puppetlabs/lein-ezbake/template/global/Rakefile, resources/puppetlabs/lein-ezbake/template/global/ext/debian/control.erb, resources/puppetlabs/lein-ezbake/template/global/ext/debian/preinst.erb, resources/puppetlabs/lein-ezbake/template/global/ext/redhat/ezbake.spec.erb, resources/puppetlabs/lein-ezbake/template/global/ext/redhat/preinst.erb, resources/puppetlabs/lein-ezbake/template/global/install.sh.erb
Some customers have a requirement to have all locally created users exist in LDAP. Because the same users would be created on every system, the local users for Puppet on a new master already exist in LDAP. The check is performed, the users are determined to already exist, and then during a reboot the systemd-tmpfiles-setup fails due to ldap dependencies of the puppet userid/groups
=> (PE-24606) use luseradd instead of useradd for ldap reboot issue

CHANGELOG.md, resources/puppetlabs/lein-ezbake/template/global/ext/debian/control.erb, resources/puppetlabs/lein-ezbake/template/global/ext/debian/preinst.erb, resources/puppetlabs/lein-ezbake/template/global/ext/redhat/ezbake.spec.erb, resources/puppetlabs/lein-ezbake/template/global/ext/redhat/preinst.erb, resources/puppetlabs/lein-ezbake/template/global/install.sh.erb
This commit reverts the changes made to address PE-24606. We encountered
installation failure when bumping puppetserver to a version of ezbake with
these changes. There were several issues with this work, the largest of which
being the fact that there is no libuser package for sles and there is a bug in
libuser1, a dependency of libuser, for debian 8 (jessie) and ubuntu 16.04
(xenial) (https://bugs.launchpad.net/ubuntu/+source/system-config-samba/+bug/1718202).
Working around these issues (i.e. only using libuser commands on rhel systems)
is possible, but there are several unused code paths in this repo that are
making this hard to debug. The plan is to remove those paths before retrying
this work.
Revert "add libuser dependency in the correct spot"
This reverts commit …
=> (RE-12082) Revert libuser changes

README.md, src/puppetlabs/ezbake/core.clj
In 87dcc4da73a9607ba807246c2e53adc84628f416 we removed rpm and deb
packaging artifacts that aren't used by FPM, but we did not remove the
legacy-build action that used those artifacts.
This removes the ability to build packages using anything other than
FPM.
=> (maint) Remove legacy-build

resources/puppetlabs/lein-ezbake/template/pe/ext/build_defaults.yaml
This commit removes sles-11 and ubuntu-14.04 (trusty) from the list of
platforms to build for PE. We have not supported these platforms as masters
since before 2018.1 (Irving).
=> (maint) Remove EOL master platforms from list of cows and mocks

CHANGELOG.md
I forgot to update the changelog before tagging so thats why it skips 2.0.2
=> (maint) Update CHANGELOG for 2.0.3 release

resources/puppetlabs/lein-ezbake/template/global/ext/redhat/preinst.erb
It looks like we were treating `additiona_preinst` as a string in the
rpm preinst, but it's an array. Iterate over the array to get these into
the packages correctly.
=> (maint) Additional preinstall scripts weren't added properly

resources/puppetlabs/lein-ezbake/template/global/ext/cli/foreground.erb, resources/puppetlabs/lein-ezbake/template/global/ext/cli/start.erb
On OpenJDK 8 the security.egd and securerandom.sourcefile parameters,
if set, should have a protocol attached their path. When using
`-Djava.security.debug=provider` one can see this error with the
previous value:
```
puppetserver[24654]: provider: Failed to create seed generator with /dev/urandom: java.net.MalformedURLException: no protocol: /dev/urandom
```
With this change service start up time (measure with just
`while true; do time systemctl restart puppetserver; done`)
goes from 27 seconds on redhat 7 to 20 seconds and from 23 seconds on
debian 8 to 18 seconds.
I should note that removing this line completely also has the same
effect. It appears that in OpenJDK 8 and above the JVM simply does the
right thing. Instead of removing the line I've left if for FOSS users
that may be using …
=> (maint) Use proper file format for random source

.dockerignore, .gitignore, docker/Gemfile, docker/Makefile, docker/README.md, docker/distelli-manifest.yml, docker/ezbake/Dockerfile, docker/ezbake/docker-entrypoint.sh, docker/spec/ezbake_spec.rb
This commit adds artifacts needed to build and test an ezbake container.
This should help with development and testing, both internal to Puppet
and for external contributors.
=> (maint) Add docker container for ezbake builds

resources/puppetlabs/lein-ezbake/template/global/controller.sh.erb
By default, RPM summaries are the first line of the package
descriptions. Due to https://github.com/jordansissel/fpm/issues/1468, we
had originally set the descriptions to not include newlines. Since this
is causing the full description to end up in the summary, use the
`$(printf ...)` work-around.
=> (maint) Update package descriptions to use newlines

resources/puppetlabs/lein-ezbake/template/global/ext/cli/foreground.erb, resources/puppetlabs/lein-ezbake/template/global/ext/cli/start.erb
This setting is of little value in Java 8+ and we've seen no difference
anecdotally between explicitly configuring /dev/urandom as a source vs
using the JVMs defaults.
We will be explicitly setting this to /dev/random for FIPS enabled
builds, however we will do so via the JAVA_ARGS variable. FOSS users who
would like to manage their egd source should use JAVA_ARGS as well.
=> (SERVER-2602) Do not manage egd

resources/puppetlabs/lein-ezbake/template/global/tasks/build.rake
!! Pkg::Util::Version.fail_on_dirty_source is deprecated. Please use
Pkg::Util::Git.fail_on_dirty_source instead.
=> (maint) fix up deprecation warning

README.md
It turns out that `cli-defaults.sh.erb` only works in standalone
projects, and not part of an uberjar project.  This updates the
readme to reflect that.
=> (maint) improve documentation for cli-defaults

resources/puppetlabs/lein-ezbake/template/global/ext/fpm.rb
Reverts puppetlabs/ezbake#561
We have added these tools to our test pipelines, we don't need to depend on them in the packages
=> Revert "(maint) Add rng-tools as a dependency on redhatfips"

CHANGELOG.md
This reverts commit fe5919e5a52ba3b7e6f20b5e7a6fbfaa2006f46e.
This version was never released because we ended up reverting the only change
it would have included.
=> Revert "(maint) Update changelog for 2.1.6 release"

CHANGELOG.md, resources/puppetlabs/lein-ezbake/template/global/controller.sh.erb, resources/puppetlabs/lein-ezbake/template/global/install.sh.erb
This option isn't supported with the version of systemd that ships with
Debian 8, so comment out that line at install time.
=> (RE-12523) Don't set `TasksMax` in the service file for Debian 8

CHANGELOG.md, resources/puppetlabs/lein-ezbake/template/global/ext/fpm.rb
=> (EZ-135) PE packages should depend on pe-bouncy-castle-jars

CHANGELOG.md, src/puppetlabs/ezbake/core.clj
This commit adds a method to copy build-scripts from the current project to the
staging dir. Previously, we only copied build-scripts from direct dependencies,
which resulted in the FOSS puppetserver build-scripts to be used instead of the
pe-puppet-server-extensions build-scripts when building from pe-pse instead of
from pe-puppetserver (PE-28810).
It appears that puppetserver gets around this by declaring a dependency on
itself in the :ezbake profile.
=> (EZ-35) Make use of project build-scripts

src/puppetlabs/ezbake/core.clj
Previously, ezbake would search all of the dependencies that it compiled
into the uberjar for ezbake config resources (e.g. CLI scripts and conf
files). However, we have a usecase now where one ezbake project is
wrapping another standalone ezbake project, so we want to exclude the
config from the wrapped project (puppetserver) and just use the fixtures
from the wrapping project (pe-puppetserver).
This commit adds a value, `excluded-ezbake-deps` to the `lein-ezbake`
config section, which contains a list of project symbols. These projects
will not be searched for packaging resources, but they will still be
included for compiling.
=> (EZ-140) Allow excluding projects from ezbake resource search

CHANGELOG.md, resources/puppetlabs/lein-ezbake/template/global/ext/cli/start.erb
This commit makes a small correction to the OnOutOfMemoryError flag
used when starting JVMs when the Java version is older than 11.
Prior to this commit, the nested quoting of the argument for the
OnOutOfMemoryError flag resulted in Java attempting to execute
"kill -9 %p" as a single binary name instead of executing "kill"
and passing "-9" and "%p" as arguments.
=> (EZ-142) Fix OnOutOfMemoryError flag used for older Javas

CHANGELOG.md, resources/puppetlabs/lein-ezbake/template/global/ext/cli/foreground.erb
Ran into this adjusting k8s pods to runas the service user. In this
case, the foreground command is already being executed as the service
user and attempts to become that user fail as it doesn't have privileges
to redundantly become itself anyway.
=> (REPLATS-150) Skip efforts to run as user when already service user

CHANGELOG.md, resources/puppetlabs/lein-ezbake/template/foss/ext/build_defaults.yaml
=> (EZ-145) Remove debian 8 from build targets

CHANGELOG.md, resources/puppetlabs/lein-ezbake/template/foss/ext/build_defaults.yaml, resources/puppetlabs/lein-ezbake/template/global/ext/fpm.rb
Debian 11 is not able to easily install Java 8, so like Debian 10 and
Ubunutu 20.04, we make packages depend on Java 11 instead.
=> (RE-14469) Add debian 11 as a default FOSS platform

CHANGELOG.md, docker/README.md, resources/puppetlabs/lein-ezbake/template/foss/ext/build_defaults.yaml
=> (maint) Removded pl-el-6-i386 and base-xenial-i386.cow as build defaults for foss.

CHANGELOG.md, resources/puppetlabs/lein-ezbake/template/global/ext/fpm.rb
This was mistakenly changed, it was previously getting the default from the top of fpm.rb
=> (PDB-5622) Fix EL java dependency on Platform 7

CHANGELOG.md, resources/puppetlabs/lein-ezbake/template/foss/ext/build_defaults.yaml, resources/puppetlabs/lein-ezbake/template/pe/ext/build_defaults.yaml
=> (RE-15440,RE-15456) Add ubuntu 22.04 as a FOSS and PE server build target

CHANGELOG.md, resources/puppetlabs/lein-ezbake/template/global/ext/fpm.rb
With the release of openjdk-headless 11.0.20.0.8-2.el8 tzdata-java is no longer included as a dependency of openjdk. This causes startup failures in puppetserver when it isn't present.  This adds an explicit dependency on the package, which is small, and is required.
=> (maint) add tzdata-java as dependency on el-7 and above platforms

CHANGELOG.md, resources/puppetlabs/lein-ezbake/template/global/ext/fpm.rb
Previously we were silently failing to specify a java dependency for Puppet Platform 8 builds on RedHat 9.
Add an error message that should help diagnose this issue for future redhat releases, and specify java 17 as a package dependency.
=> (maint) Fix el9 platform 8 builds

CHANGELOG.md, resources/puppetlabs/lein-ezbake/staging-templates/project_data.yaml.mustache, resources/puppetlabs/lein-ezbake/template/global/ext/ezbake.needrestart.conf.erb, resources/puppetlabs/lein-ezbake/template/global/install.sh.erb
In Ubuntu 22, needrestart is now called by default whenever a package is installed via apt. Because our packages lay down a temp directory for use by the service, when the services create and modify files in those temp dirs, needrestart thinks the service needs to be restarted. Because we manage restarting our services as needed, this drops a file in /etc/needrestart/conf.d that adds the service to the list of services needrestart should ignore.
Note that this will drop the file regardless of if needrestart is present on the system (e.g. Ubuntu 18), but it should be harmless if needrestart isn't present.
=> (PE-36861) Add a needrestart conf file for debian packages

CHANGELOG.md, resources/puppetlabs/lein-ezbake/template/global/ext/fpm.rb
currently puppetserver 7 is not installable on sles > 12 because java 8 is no longer shipped with the OS.
=> (maint) adjust sles java requirements

CHANGELOG.md, README.md, src/leiningen/ezbake_core.clj, src/puppetlabs/ezbake/core.clj, src/puppetlabs/ezbake/dependency_utils.clj
=> (PE-37713) Copy files included with `:include-dir` to staging directory
