puppetlabs/ezbake

CHANGELOG.md
Added changelog and bumped the version number.
=> (maint) 0.3.21 release prep

README.md
This adds docs describing how to use the new ezbake settings
=> (EZ-78) Docs for bootstrap work

CHANGELOG.md, project.clj
Bump Y version for feature release
=> (MAINT) Update changelog/version for 0.5.0 release

CHANGELOG.md
@cprice404, @shrug - Could you take a quick peek at this?  Probably stuff unrelated to the 'reload' work that I left out, not sure.
=> (MAINT) Update CHANGELOG.md for 1.0.0 release

src/leiningen/ezbake.clj, src/puppetlabs/ezbake/core.clj
This commit adds some schema validation of the ezbake project config
before starting the package staging phase.
=> (MAINT) Schema validate ezbake config before staging package

README.md
This commit adds some documentation to the ezbake README.md for the CLI
subcommands, including sections for each of the standard subcommands
that EZBake includes in all packages.
=> (EZ-94) Add some README.md documentation for CLI subcommands

resources/puppetlabs/lein-ezbake/template/foss/ext/build_defaults.yaml
We should not be building any projects for this platform
=> (maint) Fedora 21 has reached end of life

README.md, src/puppetlabs/ezbake/core.clj, src/puppetlabs/ezbake/dependency_utils.clj
To make sure we can have non-reproducible builds for testing.
=> Merge stable to master

README.md, resources/puppetlabs/lein-ezbake/staging-templates/ezbake.rb.mustache, resources/puppetlabs/lein-ezbake/staging-templates/project_data.yaml.mustache, resources/puppetlabs/lein-ezbake/template/global/ext/cli/foreground.erb, resources/puppetlabs/lein-ezbake/template/global/ext/cli/start.erb, resources/puppetlabs/lein-ezbake/template/global/install.sh.erb, src/puppetlabs/ezbake/core.clj
This commit adds support for installing additional uberjars retrieved from
maven coordinates in a project.clj file
=> (SERVER-1772) Install additional uberjars

resources/puppetlabs/lein-ezbake/staging-templates/ezbake.rb.mustache, resources/puppetlabs/lein-ezbake/template/global/controller.sh.erb, resources/puppetlabs/lein-ezbake/template/global/ext/fpm.rb, src/puppetlabs/ezbake/core.clj
Add rpm triggers into the project.clj file under `:lein-ezbake` of the project you want to have triggers:
`redhat-postinst-install-triggers [ { :package "<package-name>", :script [<array of scripts>] } ]`
`redhat-postinst-upgrade-triggers [ { :package "<package-name>", :script [<array of scripts>] } ]`
=> (EZ-111) Add support for RPM triggers

resources/puppetlabs/lein-ezbake/staging-templates/ezbake.rb.mustache, resources/puppetlabs/lein-ezbake/template/global/controller.sh.erb, resources/puppetlabs/lein-ezbake/template/global/ext/debian/postinst.erb, resources/puppetlabs/lein-ezbake/template/global/ext/fpm.rb, src/puppetlabs/ezbake/core.clj
(rebase/merge after https://github.com/puppetlabs/ezbake/pull/448 is merged)
=> (EZ-113) Add support for debian triggers

resources/puppetlabs/lein-ezbake/template/global/tasks/build.rake
The generic ezbake jenkins jobs now have MOCKS and COWS parameters to
help with determining repo creation. We should make sure we're passing
local mock/cow values through so we create repos correctly.
=> (maint) Pass MOCK and COW settings when running `lein ezbake build`

resources/puppetlabs/lein-ezbake/template/global/tasks/build.rake
For debian repos with no apt_repo_name set, the packaging tasks that
generate the repo look for artifacts under deb/dist, rather than
deb/dist/main as it had originally appeared. This fixes the code to
match the assumptions in packaging.
=> (maint) Undo some bad assumptions from packaging hard-coding

project.clj
We are making the change from nexus to artifactory. [test here](https://artifactory.delivery.puppetlabs.net/artifactory/webapp/#/search/quick/eyJzZWFyY2giOiJxdWljayIsInF1ZXJ5IjoibGVpbi1lemJha2UtMS43LjEifQ==)
=> (RE-9801) Use artifactory instead of nexus

resources/puppetlabs/lein-ezbake/template/foss/ext/build_defaults.yaml, resources/puppetlabs/lein-ezbake/template/pe/ext/build_defaults.yaml
This reverts commit 9bea7d1b29099b5981f1397167271f6b05cc30cb.
=> Revert "Revert "Merge pull request #450 from melissa/ticket/master/update-to-packaging-1.0.x""

CHANGELOG.md, resources/puppetlabs/lein-ezbake/template/global/Gemfile, resources/puppetlabs/lein-ezbake/template/global/install.sh.erb
see individual commit messages for details
=> (RE-11573) Add fpm gem and hard-code rubylibdir + prep for 1.8.9 release

CHANGELOG.md, resources/puppetlabs/lein-ezbake/template/global/Gemfile, resources/puppetlabs/lein-ezbake/template/global/install.sh.erb
This is all cherry-picks. See individual commit messages for details.
=> (RE-11573) Backports from master

resources/puppetlabs/lein-ezbake/template/foss/ext/build_defaults.yaml, resources/puppetlabs/lein-ezbake/template/global/controller.sh.erb, resources/puppetlabs/lein-ezbake/template/global/ext/fpm.rb, resources/puppetlabs/lein-ezbake/template/global/tasks/build.rake, resources/puppetlabs/lein-ezbake/template/pe/ext/build_defaults.yaml
=> (RE-12428) Add support for redhatfips-7

docker/Makefile
This follows the pattern we use for all the pupperware containers
=> (maint) Publish container readme when new container is pushed

.github/pull_request_template.md, CHANGELOG.md
make the changelog look like the ones in packaging/ezbake w unreleased section + links. didn't want to add a link for every previous release, so only added it for the last 5.
=> (RE-12861) Add pull request template + update changelog

.github/workflows/docker.yml, docker/Makefile, docker/distelli-manifest.yml
No changelog needed for this I don't think, since it's just a change in what tool we use to build the ezbake docker container.
=> Migrate pipelines to actions

resources/puppetlabs/lein-ezbake/template/global/ext/cli/start.erb
=> (EZ-132) Change the wired-in settings for Java OOM handling.

CHANGELOG.md
=> (maint) Prep for 2.1.6 release

CHANGELOG.md, resources/puppetlabs/lein-ezbake/template/global/ext/debian/postinst.erb, resources/puppetlabs/lein-ezbake/template/global/ext/redhat/postinst.erb
=> (maint) Fix issue where postinst steps don't make it into packaging

resources/puppetlabs/lein-ezbake/template/global/tasks/build.rake
The 'build?token=' access method (aka Trigger builds remotely) does not work in the latest jenkins core version.
But using the other original case where JENKINS_USER_AUTH=<LDAP username>:<token>
should work.
=> Update build.rake because of stricter jenkins security rules

CHANGELOG.md
=> prep for 2.1.7 release

CHANGELOG.md, resources/puppetlabs/lein-ezbake/template/global/ext/debian/postinst.erb, resources/puppetlabs/lein-ezbake/template/global/ext/redhat/postinst.erb
install.sh handles the postinst scripts
=> Revert postinst 'fix'

.travis.yml, ext/bin/require-leiningen
=> Make travis-ci run tests on commit.

CHANGELOG.md, project.clj
=> (EZ-140) Update changelog for excluded resources setting

CHANGELOG.md, resources/puppetlabs/lein-ezbake/template/foss/ext/build_defaults.yaml
=> (RE-13571) Add support for ubuntu-20.04 (focal) for FOSS only

CHANGELOG.md, resources/puppetlabs/lein-ezbake/template/global/ext/fpm.rb
=> (CPR-753) Change permissions of logdir

CHANGELOG.md, resources/puppetlabs/lein-ezbake/template/foss/ext/build_defaults.yaml, resources/puppetlabs/lein-ezbake/template/pe/ext/build_defaults.yaml
=> (RE-13425) Update the GPG signing key in the build_default templates

CHANGELOG.md
=> prep for release

CHANGELOG.md, resources/puppetlabs/lein-ezbake/template/global/tasks/build.rake
- Update jenkins host names
- Use '--location' flag to curl to follow redirects
- Tighten the code a little bit.
=> (EZ-146) Update for new jenkins locations.

CHANGELOG.md
=> (maint) prep for release

CHANGELOG.md, resources/puppetlabs/lein-ezbake/template/global/ext/fpm.rb
=> (maint) use rpm digest sha256

CHANGELOG.md
=> (maint) prepare for 2.3.0 release

resources/puppetlabs/lein-ezbake/template/pe/ext/build_defaults.yaml
=> (RE-14406) Add redhatfips8 to build_defaults for pe

CHANGELOG.md
=> (RE-14406) Update changelog for 2.4.0 release

CHANGELOG.md
=> (RE-14406) Fix release version in CHANGELOG.

.github/workflows/snyk_merge.yaml
=> (PE-33609) add snyk monitoring

CHANGELOG.md
=> (maint) Update changelog for 2.3.2 release

CHANGELOG.md, docker/README.md, resources/puppetlabs/lein-ezbake/template/foss/ext/build_defaults.yaml
=> (EZ-149) remove debian9 aka stretch

CHANGELOG.md, resources/puppetlabs/lein-ezbake/template/global/ext/cli/start.erb
=> (PE-36182) Add logappender=F1 arg to clojure app start

README.md
This updates the README with some information about behvior that wasn't necessarily obvious, and helpful for composite projects.
=> (maint) update README with learnings about composite project behavior

CHANGELOG.md, README.md, project.clj, src/leiningen/ezbake_core.clj
=> (PE-37713) Add `:include-dir` option in `:resources` section of a project
